### ISSUE TITLE
Use traditional Shamir Secret Sharing instead of Adept

### ISSUE THREAD

**Issue by ShivanKaul** [ShivanKaul/star-spec#19]
Using Adept SS makes the security proofs simpler, but for interop ease we should just use regular Shamir Secret Sharing.

**Comment by alxdavids** [comment]
We may need robustness to counter the issue raised by Eric Rescorla at the PPM meeting: if a malicious user creates a bad share but we have at least K good shares, then we still want to be able to recover the correct value. Adept secret sharing provides this, but we may be able to get a more efficient alternative using something like: https://www.cwi.nl/system/files/Fehr.pdf

**Comment by chris-wood** [comment]
After revisiting the ADSS paper, I'm not sure robustness is the desired property here. Instead, what we want is authenticity, which ADSS does provide. At this point, I think it would make sense to specify the ADSS syntax directly in the spec since we know it provides at least protection against the trivial DoS attack.

**Comment by chris-wood** [comment]
This has been done, so the issue can probably be closed @ShivanKaul.
